// <auto-generated />
namespace GuitarApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddSetlists : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSetlists));
        
        string IMigrationMetadata.Id
        {
            get { return "202010272245124_AddSetlists"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
